### ISSUE TITLE
case where # conditions used for RSA is fewer than the total available for estimating GSN?

### ISSUE THREAD

**Issue by jacob-prince** [cvnlab/GSN#2]
say a user wants to use the full set of stimuli available per subject to estimate the signal/noise mean and covariance structure, but then wants a noise ceiling estimate for the case where only a subset of those stimuli are being compared via RSA against some model. 

right now the "ncond" for monte carlo simulation is always the dimensionality of the input data over the condition dimension. do we want to add an input argument so that the user can optionally select a different (lower) ncond? will this affect NC estimates?

**Comment by kendrickkay** [comment]
This is an interesting issue.   In theory, the number of conditions simulated in the Monte Carlo simulations shouldn't fundamentally change the noise ceiling estimates.  (However, of course, the expectation is the larger the number of conditions, the better, for averaging out incidental variability.)   Nonetheless, would be good to implement as an optional input parameter.  I'll do this soon

**Comment by kendrickkay** [comment]
this has been implemented (as input option <ncconds>)
